[tool.poetry]
name = "safety-gymnasium-drones"
version = "0.1.0"
description = ""
authors = ["hggforget <1242537651@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
